import { Section, SectionHeader, AnimatedReveal } from "@/components/common";
import { MAP_DOTS, MAP_WIDTH, MAP_HEIGHT, projectLonLat } from "@/assets/worldDotMap";
import styles from "./CoverageMap.module.css";

/**
 * Coverage, drawn on a dot-grid world map.
 *
 * The map is ORIGINAL ARTWORK generated by `scripts/generate-dot-map.mjs` from
 * coarse hand-written continent polygons — no mapping library, no tile provider,
 * no third-party map file. The generated dots ship as plain data, so the page
 * does no geometry work at runtime.
 *
 * Two pin states carry the section's actual claim: LIVE cities are places a
 * rider can get a bike today; UPCOMING ones are expansion targets. A single pin
 * style would read as "we operate here" for all five, which is not true.
 *
 * Pins sit at real projected coordinates. LABELS are offset with a leader line —
 * Pune, Bengaluru and Chennai are within ~18px of each other at world scale, so
 * labels at the pins would overlap into an unreadable stack.
 */
export function CoverageMap({ content, id }) {
  const headingId = `${id}-heading`;
  const live = content.markers.filter((m) => m.status === "live");
  const upcoming = content.markers.filter((m) => m.status === "upcoming");

  return (
    <Section id={id} tone="inverse" ariaLabelledBy={headingId}>
      <SectionHeader
        eyebrow={content.eyebrow}
        heading={content.heading}
        subheading={content.subheading}
        headingId={headingId}
        align="center"
        className={styles.header}
      />

      <AnimatedReveal className={styles.wrap}>
        <div className={styles.legend}>
          <span className={styles.legendItem}>
            <span className={`${styles.dot} ${styles.dotLive}`} aria-hidden="true" />
            {content.liveLabel}
          </span>
          <span className={styles.legendItem}>
            <span className={`${styles.dot} ${styles.dotUpcoming}`} aria-hidden="true" />
            {content.upcomingLabel}
          </span>
        </div>

        <div className={styles.mapScroll}>
          {/*
            Decorative: every city and its status is written out in the lists
            below, which is what a screen reader reads. Labelling the SVG too
            would announce all five twice.
          */}
          <svg
            className={styles.map}
            viewBox={`0 0 ${MAP_WIDTH} ${MAP_HEIGHT}`}
            aria-hidden="true"
            focusable="false"
          >
            <g className={styles.land}>
              {MAP_DOTS.map(([x, y]) => (
                <circle key={`${x}-${y}`} cx={x} cy={y} r="1.7" />
              ))}
            </g>

            {content.markers.map((m) => {
              const [px, py] = projectLonLat(m.lon, m.lat);
              // Small deliberate offsets so close-together pins stay separate.
              const x = px + (m.nudgeX ?? 0);
              const y = py + (m.nudgeY ?? 0);
              const lx = x + m.labelDx;
              const ly = y + m.labelDy;
              const isLive = m.status === "live";

              return (
                <g key={m.id} className={isLive ? styles.pinLive : styles.pinUpcoming}>
                  <line className={styles.leader} x1={x} y1={y} x2={lx} y2={ly} />
                  {isLive ? <circle className={styles.halo} cx={x} cy={y} r="5.5" /> : null}
                  <circle className={styles.pin} cx={x} cy={y} r="2.6" />
                  <text
                    className={styles.pinLabel}
                    x={lx + (m.anchor === "end" ? -3 : 3)}
                    y={ly + 3}
                    textAnchor={m.anchor}
                  >
                    {m.name}
                  </text>
                </g>
              );
            })}
          </svg>
        </div>

        <div className={styles.lists}>
          {[
            { label: content.liveLabel, items: live, live: true },
            { label: content.upcomingLabel, items: upcoming, live: false },
          ].map((group) => (
            <div key={group.label}>
              <h3 className={styles.listHeading}>{group.label}</h3>
              <ul className={styles.list}>
                {group.items.map((m) => (
                  <li key={m.id} className={styles.city}>
                    <span
                      className={`${styles.dot} ${group.live ? styles.dotLive : styles.dotUpcoming}`}
                      aria-hidden="true"
                    />
                    {m.name}
                    <span className={styles.country}>{m.country}</span>
                  </li>
                ))}
              </ul>
            </div>
          ))}
        </div>
      </AnimatedReveal>
    </Section>
  );
}

export default CoverageMap;
